name: Build C++ Meson Project

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Meson and Ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Setup MSVC
        uses: microsoft/setup-msbuild@v1.3

      - name: Configure Meson (Debug)
        if: matrix.build_type == 'debug'
        run: |
          meson setup build/debug --buildtype=debug

      - name: Configure Meson (Release)
        if: matrix.build_type == 'release'
        run: |
          meson setup build/release --buildtype=release

      - name: Build Debug
        if: matrix.build_type == 'debug'
        run: |
          meson compile -C build/debug

      - name: Build Release
        if: matrix.build_type == 'release'
        run: |
          meson compile -C build/release

      - name: Test Debug Build
        if: matrix.build_type == 'debug'
        run: |
          cd build/debug
          .\cpp_meson_demo.exe

      - name: Test Release Build
        if: matrix.build_type == 'release'
        run: |
          cd build/release
          .\cpp_meson_demo.exe

      - name: Prepare Debug Artifacts
        if: matrix.build_type == 'debug'
        run: |
          mkdir debug-artifacts
          copy build\debug\cpp_meson_demo.exe debug-artifacts\
          copy build\debug\*.pdb debug-artifacts\ 2>nul || echo "No PDB files found"

      - name: Prepare Release Artifacts
        if: matrix.build_type == 'release'
        run: |
          mkdir release-artifacts
          copy build\release\cpp_meson_demo.exe release-artifacts\

      - name: Upload Debug Artifacts
        if: matrix.build_type == 'debug'
        uses: actions/upload-artifact@v4
        with:
          name: debug-build-windows
          path: debug-artifacts/
          retention-days: 30

      - name: Upload Release Artifacts
        if: matrix.build_type == 'release'
        uses: actions/upload-artifact@v4
        with:
          name: release-build-windows
          path: release-artifacts/
          retention-days: 30
